js:
  - '@OroNavigationBundle/Resources/public/js/jquery.form.js'
  - '@OroNavigationBundle/Resources/public/js/hash.navigation.js'
  - '@OroNavigationBundle/Resources/public/js/url.min.js'

  - '@OroNavigationBundle/Resources/public/js/models/navigation.item.js'
  - '@OroNavigationBundle/Resources/public/js/collections/navigation.js'
  - '@OroNavigationBundle/Resources/public/js/views/navigation.abstract.js'
  - '@OroNavigationBundle/Resources/public/js/views/dot.menu.item.js'
  - '@OroNavigationBundle/Resources/public/js/views/dot.menu.js'

  - '@OroNavigationBundle/Resources/public/js/models/pinbar.item.js'
  - '@OroNavigationBundle/Resources/public/js/models/pagestate.js'

  - '@OroNavigationBundle/Resources/public/js/collections/pinbar.js'
  - '@OroNavigationBundle/Resources/public/js/views/pinbar.item.js'
  - '@OroNavigationBundle/Resources/public/js/views/pinbar.js'
  - '@OroNavigationBundle/Resources/public/js/views/pagestate.js'

  - '@OroNavigationBundle/Resources/public/js/views/favorites.js'
  - '@OroNavigationBundle/Resources/public/js/views/shortcuts.js'
