config:
    shim:
        'routing':
            exports: 'window.Routing'
        'jquery.form':
            deps:
                - 'jquery'
        'url':
            exports: 'Url'
    paths:
        'routing': 'bundles/fosjsrouting/js/router.js'
        'jquery.form': 'bundles/oronavigation/lib/jquery.form.js'
        'url': 'bundles/oronavigation/lib/url.min.js'
        'oronavigation/js/content/grid-builder': 'bundles/oronavigation/js/content/grid-builder.js'
        'oronavigation/js/shortcuts/view': 'bundles/oronavigation/js/shortcuts/view.js'

        'oronavigation/js/app/modules/views': 'bundles/oronavigation/js/app/modules/views.js'
        'oronavigation/js/app/modules/content-manager': 'bundles/oronavigation/js/app/modules/content-manager.js'
        'oronavigation/js/app/views/history-view': 'bundles/oronavigation/js/app/views/history-view.js'
        'oronavigation/js/app/views/most-viewed-view': 'bundles/oronavigation/js/app/views/most-viewed-view.js'
        'oronavigation/js/app/models/base/model': 'bundles/oronavigation/js/app/models/base/model.js'
        'oronavigation/js/app/views/favorite/main-view': 'bundles/oronavigation/js/app/views/favorite/main-view.js'
        'oronavigation/js/app/views/pin/main-view': 'bundles/oronavigation/js/app/views/pin/main-view.js'
        'oronavigation/js/app/models/page-state-model': 'bundles/oronavigation/js/app/models/page-state-model.js'
        'oronavigation/js/app/views/page-state-view': 'bundles/oronavigation/js/app/views/page-state-view.js'
    appmodules:
        - oronavigation/js/app/modules/views
        - oronavigation/js/app/modules/content-manager
