config:
    shim:
        'routing':
            exports: 'window.Routing'
        'jquery.form':
            deps:
                - 'jquery'
        'url':
            exports: 'Url'
    paths:
        'routing': 'bundles/fosjsrouting/js/router.js'
        'jquery.form': 'bundles/oronavigation/lib/jquery.form.js'
        'url': 'bundles/oronavigation/lib/url.min.js'
        'oronavigation/js/app/module': 'bundles/oronavigation/js/app/module.js'
        'oronavigation/js/navigation': 'bundles/oronavigation/js/navigation.js'
        'oronavigation/js/content/grid-builder': 'bundles/oronavigation/js/content/grid-builder.js'
        'oronavigation/js/pagestate/model': 'bundles/oronavigation/js/pagestate/model.js'
        'oronavigation/js/pagestate/view': 'bundles/oronavigation/js/pagestate/view.js'
        'oronavigation/js/pinbar/collection': 'bundles/oronavigation/js/pinbar/collection.js'
        'oronavigation/js/pinbar/item-view': 'bundles/oronavigation/js/pinbar/item-view.js'
        'oronavigation/js/pinbar/model': 'bundles/oronavigation/js/pinbar/model.js'
        'oronavigation/js/pinbar/view': 'bundles/oronavigation/js/pinbar/view.js'
        'oronavigation/js/shortcuts/view': 'bundles/oronavigation/js/shortcuts/view.js'
    appmodules:
        - oronavigation/js/app/module
