Oro\Bundle\NavigationBundle\Entity\PageState:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: pageHash
    properties:
        pageId:
            - NotBlank:     ~
            - Length:
                max:        4000
        user:
            - NotBlank:     ~
        data:
            - NotBlank:     ~

Oro\Bundle\NavigationBundle\Entity\MenuUpdate:
    constraints:
        - Oro\Bundle\NavigationBundle\Validator\Constraints\MaxNestedLevel: ~
        - Oro\Bundle\NavigationBundle\Validator\Constraints\MaxNestedLevel:
            groups: move
    properties:
        titles:
            - Valid: ~
        uri:
            - NotBlank: ~
