datagrids:
    menu-base-grid:
        source:
            type: menu-update-default-provider
        columns:
            name:
                label: oro.navigation.menuitem.name.label
        properties:
            view_link:
                route: oro_navigation_user_menu_view
                type: url
                params:
                    menuName: name
        actions:
            view:
                type: navigate
                label: oro.grid.action.view
                link: view_link
                icon: eye-open
                rowAction: true
        options:
            toolbarOptions:
                hide: true

    menu-user-grid:
        extends: menu-base-grid
        properties:
            view_link:
                route: oro_navigation_user_menu_view
