navigation:
    menu_config:
        templates:
            application_menu:
                template: 'OroNavigationBundle:Menu:application_menu.html.twig'
                currentClass: 'active'
                ancestorClass: 'active'
                allow_safe_labels: true
                rootClass: 'nav nav-multilevel main-menu'
            dots_menu:
                template: 'OroNavigationBundle:Menu:dots_menu.html.twig'
            shortcuts:
                template: 'OroNavigationBundle:Menu:shortcuts.html.twig'
            navbar:
                template: 'OroNavigationBundle:Menu:navbar.html.twig'
            dropdown:
                template: 'OroNavigationBundle:Menu:dropdown.html.twig'
            horizontal_tabs:
                template: 'OroNavigationBundle:Menu:horizontal_tabs.html.twig'
            pinbar:
                template: 'OroNavigationBundle:Menu:pinbar.html.twig'
            favorite:
                template: 'OroNavigationBundle:Menu:favorites.html.twig'
            mostviewed:
                template: 'OroNavigationBundle:Menu:mostviewed.html.twig'
                rootClass: 'extra-list'
            history:
                template: 'OroNavigationBundle:Menu:history.html.twig'
                rootClass: 'extra-list'
                currentAsLink: false

        items:
            pinbar:
                label: 'oro.navigation.menu.pinbar.label'
                extras:
                    icon: 'icon-folder-close'
                    maxItems: 10
                uri: '#'
            history:
                label: 'oro.navigation.menu.history.label'
                extras:
                    icon: 'icon-time'
                    activeIfFirstIsEmpty: true
                uri: '#'
            favorite:
                label: 'oro.navigation.menu.favorite.label'
                extras:
                    icon: 'icon-star-empty'
                uri: '#'
            mostviewed:
                label: 'oro.navigation.menu.mostviewed.label'
                extras:
                    icon: 'icon-flag'
                uri: '#'
            menu_list_default:
                label: 'oro.navigation.menu.menu_list_default.label'
                route: 'oro_navigation_org_menu_index'
                extras:
                    position: 90
                    routes: ['/^oro_navigation_org_menu_[\w_]+$/']
                    description: 'Manage menus in default area'

        tree:
            application_menu:
                type: application_menu
                children:
                    system_tab:
                        children:
                            menu_list_default: ~

            dots_menu:
                type: dots_menu
                children:
                    history: ~
                    favorite: ~
                    mostviewed: ~

            shortcuts:
                type: shortcuts

    titles:
        oro_shortcut_actionslist: 'Shortcut Actions List'
        oro_pinbar_help: 'How To Use Pinbar'

        oro_navigation_user_menu_index: '%%username%% - Menus'
        oro_navigation_user_menu_view: '%%title%% - Menus - %%username%%'
        oro_navigation_user_menu_create: 'Create Menu Item - Menus - %%username%%'
        oro_navigation_user_menu_update: '%%title%% - Edit - Menus - %%username%%'
        oro_navigation_org_menu_index: ~
        oro_navigation_org_menu_view: '%%title%%'
        oro_navigation_org_menu_create: 'Create Menu Item'
        oro_navigation_org_menu_update: '%%title%% - Edit'

    navigation_elements:
        pinButton:
            default: true

        favoriteButton:
            default: true
